name: SSH to GCP VM

on:
  push:
    branches:
      - main  # Ganti dengan branch yang Anda inginkan

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to GCP VM
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: 'tes-app'  # Ganti dengan nama instance Anda
          zone: 'asia-southeast2-b'  # Ganti dengan zona instance Anda
          user: 'madolcheworld'  # Ganti dengan username Anda di VM
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          command: 'ls -la /home'  # Perintah yang ingin Anda jalankan di VM
